export default {
    LOCATION_CHANGE: 'LOCATION_CHANGE',
    LOADING: 'LOADING',
    LIST_LOADED: 'LIST_LOADED',
    LIST_DATA_LOADED: 'LIST_DATA_LOADED',
    ITEM_LOADED: 'ITEM_LOADED',
    ITEM_DATA_LOADED: 'ITEM_DATA_LOADED',
}